--
--    Copyright (C) 2006-2011 Serotonin Software Technologies Inc. All rights reserved.
--    @author Matthew Lohbihler
--
create table pointLinks (
  id int not null generated by default as identity (start with 1, increment by 1),
  xid varchar(50) not null,
  sourcePointId int not null,
  targetPointId int not null,
  script clob,
  eventType int not null,
  writeAnnotation char(1) not null,
  disabled char(1) not null
);
alter table pointLinks add constraint pointLinksPk primary key (id);
alter table pointLinks add constraint pointLinksUn1 unique (xid);
